apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-xt55
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vleq-tenant/status-quarkus-io/statusquarkusio-xt55@sha256:3714ef42d311d46bc1ced3d52994ee6163939f530ee563cdcee76b5fc9890c72
        name: my-java-quarkus
        resources: {}
status: {}
